### ISSUE TITLE
Help implementing a webserver using net/http and gssapi/spnego

### ISSUE THREAD

**Issue by mogthesprog** [apcera/gssapi#44]
Hi guys,

I'm looking to implement a webserver in go (i'm new to go) for a small project and wanted to utilise spnego for authentication. In the documentation it refers to a reference implementation, but i can't seem to find it. Do you have one, by any chance?

Cheers,

Morgan

**Comment by philpennock** [comment]
Which docs?  I'm probably looking right past it, but I only see reference to the system GSSAPI implementation, which is the GSSAPI code library, not the GSSAPI `WWW-Negotiate:` HTTP auth mechanism.

There's example HTTP server code in `test/` in 
https://github.com/apcera/gssapi/blob/master/test/service_access.go which is referenced by `service.go` though this is really just a test driver.  Should be enough to get you started?

**Comment by mogthesprog** [comment]
Cheers @philpennock 

I found this just after i'd posted the issue... can't believe i missed it earlier. I almost have a basic working example already going from the tests :) 

The reference I was referring to was on the [spnego page] (https://www.godoc.org/github.com/apcera/gssapi/spnego) on godoc.org (at the very top).

> This is intended to give an interface for Kerberized servers to negotiate with clients using SPNEGO. A reference implementation is provided below.

Either way, Those test have helped massively. Feel free to close this, and I can post back if i get any more trouble. Thanks for the quick response btw.

**Comment by mogthesprog** [comment]
One more quick question, I've just been playing with the working example I have, and I was wondering what the significance of the following errors are:

```
go-gssapi-test-service: Err     2016/03/21 18:14:36 401 "GET" "/unwrap/" "no input token provided"
go-gssapi-test-service: Err     2016/03/21 18:14:36 500 "GET" "/unwrap/" "A required input parameter could not be read\n"
```

I get this output when i browser to the handle "/verify_mic/" in a browser. Is it a security concern?

**Comment by philpennock** [comment]
Probably being logged on the browser's first request, before the auth-needed response has told it to use GSSAPI auth to access the resource.  Haven't looked to confirm.  If memory serves (it might not, today) GSSAPI and the Kerberos mechanism within that support initial data with the client sending stuff first; with protocols which wrap auth in SASL this is known as Initial Response.

So, guessing (not investigating) the browser sends auth-less request; the server sees that, initialises a server context to generate a step for the client, doesn't pass in IR data when initialising that context and the message from the library comes from that data being empty.

I haven't played around with `apcera/gssapi` server-side support though, only client-side.  @alextoombs can confirm/deny my pseudo-analysis.

**Comment by alextoombs** [comment]
@mogthesprog: glad the tests helped! I'll update those comments; I think the tests are the best examples for now.

@philpennock is correct about the 401; [see this section in the RFC](https://tools.ietf.org/html/rfc4559#section-4.1) on SPNEGO. You get a 401 as a "challenge", and clients (should) respond with the proper header.

Thanks @philpennock!

**Comment by mogthesprog** [comment]
Great stuff. Thanks again guys, been a great help! I'll close this now.
